package boj.problems

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class No30889Test : StringSpec({
    "좌석 배치도 : https://www.acmicpc.net/problem/30889" {
        val given = """
            4
            A5
            D4
            I1
            F14
        """.trimIndent()
        val expected = """
            ....o...............
            ....................
            ....................
            ...o................
            ....................
            .............o......
            ....................
            ....................
            o...................
            ....................
        """.trimIndent()

        No30889().solve(given.reader().buffered()) shouldBe expected
    }
})
